In [55]:
import os
import matplotlib.pyplot as plt
import pandas as pd
import joblib # to save the model
import numpy as np

plt.style.use("fivethirtyeight")

In [56]:
class perceptron:
    def __init__(self, eta: float=None, epochs: int=None):# default datatype is float and int and default value is None
        self.weights=np.random.randn(3) * 1e-4 # to keep the weight value very small so the conversion/calculation become faster 1e-4 is 10**-4
        self.eta = eta # Learning rate
        self.epochs = epochs # iterations
        
    def _z_outcome(self,inputs,weights):
        return np.dot(inputs,weights)
    
    def activation_function(self,z):
        return np.where(z > 0, 1, 0)
        
    def fit(self,X,y):
        self.X = X
        self.y = y
        
        X_with_bias = np.c_[self.X, -np.ones((len(self.X), 1))] # cconcatination with bias
        print(f"X with bias: \n {X_with_bias}")
        
        for epoch in range(self.epochs):
            print("--"*10)
            print(f"for epoch>> {epoch +1}")
            print("--"*10)
            z= self._z_outcome(X_with_bias,self.weights)
            y_hat = self.activation_function(z)
            
            print(f"predicted value after forward pass: \n {y_hat}")
            
            self.error =self.y - y_hat
            print(f"error: \n {self.error}")
                  
                  
            self.weights = self.weights + self.eta * np.dot(X_with_bias.T, self.error)
            print(f"updated weights after epoch: {epoch+1}/{self.epochs}: \n{self.weights}")
            print(f"##"*10)
            
    def predict(self, X):
        X_with_bias = np.c_[X, -np.ones((len(X), 1))]
        z = self._z_outcome(X_with_bias, self.weights)
        return self.activation_function(z)

In [57]:
OR = {
    "x1" : [0,0,1,1],
    "x2" : [0,1,0,1],
    "y" : [0,1,1,1]
}

df_OR =pd.DataFrame(OR)

df_OR

x1  x2  y
0   0   0  0
1   0   1  1
2   1   0  1
3   1   1  1

In [58]:
def prepare_data(df, target_col="y"):
    X = df.drop(target_col, axis=1)
    y = df[target_col]
    
    return X,y

In [59]:
X,y = prepare_data(df_OR)
ETA = 0.1
EPOCHS = 10
model_or = perceptron(eta=ETA, epochs=EPOCHS)

model_or.fit(X,y)

X with bias: 
 [[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
--------------------
for epoch>> 1
--------------------
predicted value after forward pass: 
 [0 0 1 0]
error: 
 0    0
1    1
2    0
3    1
Name: y, dtype: int64
updated weights after epoch: 1/10: 
[ 0.10009656  0.19988707 -0.19991011]
####################
--------------------
for epoch>> 2
--------------------
predicted value after forward pass: 
 [1 1 1 1]
error: 
 0   -1
1    0
2    0
3    0
Name: y, dtype: int64
updated weights after epoch: 2/10: 
[ 0.10009656  0.19988707 -0.09991011]
####################
--------------------
for epoch>> 3
--------------------
predicted value after forward pass: 
 [1 1 1 1]
error: 
 0   -1
1    0
2    0
3    0
Name: y, dtype: int64
updated weights after epoch: 3/10: 
[1.00096560e-01 1.99887067e-01 8.98943548e-05]
####################
--------------------
for epoch>> 4
--------------------
predicted value after forward pass: 
 [0 1 1 1]
error: 
 0    0
1    0
2    0
3    0


In [63]:
model_or.predict(X)

array([0, 1, 1, 1])

In [65]:
model_or.predict(X=[[0,0]])

array([0])

# AND

In [51]:
AND = {
    "x1" : [0,0,1,1],
    "x2" : [0,1,0,1],
    "y" : [0,0,0,1]
}

df_AND =pd.DataFrame(AND)

df_AND

x1  x2  y
0   0   0  0
1   0   1  0
2   1   0  0
3   1   1  1

In [52]:
def prepare_data_and(df, target_col="y"):
    X = df.drop(target_col, axis=1)
    y = df[target_col]
    
    return X,y

In [ ]:
X,y = prepare_data_and(df_AND)
ETA = 0.1
EPOCHS = 10
model_and = perceptron(eta=ETA, epochs=EPOCHS)

model_and.fit(X,y)

In [ ]:
model_and.pr

# XOR

In [ ]:
AND = {
    "x1" : [0,0,1,1],
    "x2" : [0,1,0,1],
    "y" : [0,1,1,0]
}

df_AND =pd.DataFrame(AND)

df_AND