In [2]:
import os
import matplotlib.pyplot as plt
import pandas as pd
import joblib # to save the model
import numpy as np

plt.style.use("fivethirtyeight")

In [3]:
class perceptron:
    def __init__(self, eta: float=None, epochs: int=None):# default datatype is float and int and default value is None
        self.weights=np.random.randn(3) * 1e-4 # to keep the weight value very small so the conversion/calculation become faster 1e-4 is 10**-4
        self.eta = eta # Learning rate
        self.epochs = epochs # iterations
        
    def fit(self,X,y):
        self.X = X
        self.y = y
        
        X_with_bias = np.c_[self.X, -np.ones((len(self.X), 1))] # cconcatination with bias
        print(f"X with bias: \n {X_with_bias}")

In [5]:
obj=perceptron(eta=0.01, epochs=10)

In [6]:
obj.epochs

10

In [7]:
obj.eta

0.01

In [8]:
obj.weights

array([ 1.62980387e-04, -5.46991958e-05,  1.20904375e-05])

In [11]:
X=np.ones([4,2])

In [12]:
X

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [13]:
y=np.ones((4,1))

In [14]:
obj.fit(X,y)

X with bias: 
 [[ 1.  1. -1.]
 [ 1.  1. -1.]
 [ 1.  1. -1.]
 [ 1.  1. -1.]]
